const MESSAGE_TYPES = {
    MESSAGE_PRIVATE: 'MESSAGE_PRIVATE',
    MESSAGE_GROUP: 'MESSAGE_GROUP',
    CONFIRMATION: 'CONFIRMATION',
    HEARTBEAT: 'HEARTBEAT',
    UNKNOWN: 'UNKNOWN'
};

module.exports = MESSAGE_TYPES;